name = "karaoke-db"
main = "src/index.js"
compatibility_date = "2023-12-18"

[observability]
enabled = true
head_sampling_rate = 1

[[ d1_databases ]]
binding = "DB" # available in your Worker on env.DB
database_name = "karaoke-db"
database_id = "ba8815f1-ac9b-4279-b270-fd9bed80bc24"
